language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - desenvolvimento
install:
- sudo pip install -r requirements.txt
- sudo python setup.py sdist
addons:
  sonarqube:
    organization: amandapersampa-github
    token: gkKxHCkG3RmX5BwoH1cmi2Wz7CGmV/LsgEDJ4TZDQex5Tt251vUdnhtlBFFlATm1OQtipqRxTqJzQhOtt9NC2bCzRrvdbiDvQcA4u/DqYRjL4Kyib6Kz3hB3IceS/sqOdQppLhu2Oq6PSNfw0Gg4JZD1iWvY0He0NKfd2YJRQ11XvRFjqzaytPI/ErXCp+x29ApDno58aTdlU8NRBwFok/dmDxkAEfjo9s2mri3FiCf/i//SNkuflt6Bx9PPBGEnGgGnfNwvpLMEY1sp6PGVRIsjTEM4vetkA8nLCuWVPcXdnWhZrVWDu+jzs/mU6tmyZd5Nn4Wi4dFd1GMcCjXeE/0m43BuEy1JeVKvzR6omBNHzxMHaM+RS6m69zR0fCb8U6RDOn+wW9XGEdZfj+P4KaTJloF1j7IyFlqBruSat6dtw0cCkrBuTd+0VKczld7m86Ubkc9ethxwPPxwgtuUTghw35RRW7tjyZQMlavfb/p1UGCPyxmvJkJWjvBxQV4GbwAQiu5ccQ064YPL2LfRPv4ev5riSYvJBmAzsC+/fzomHO8ESuNGrBMKdfNgOpsdUapgvcPblPkVPnpQqGOAif65pAZkNa+BTEXa1lq+iGUv82rmRInOc4op2l0GIrf/p6xhS8vG3RgotYE40U0V87Kv8rLJCEdtHHXTnkRiy6I=
script:
- pytest
- sonar-scanner
notifications: 
slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG
env:
  global:
  - secure: FpXL932hx3BMKQd+56E3oRvWibSUyUrlCbm4588euLVQ2qwByw4a8m639gfhtQrpQzot/8H9B2bixfXJMlpZbBvfqN3uEc42rKPnVJx7iajPMDPMMeil3to9Ei1qyAFaRDZt+jk161REqYW2n9P1b0n8663AnElOOzgKsUw/0b/qaeqNvRgi9mMQ/aLSR0P43rDp/d9/4yIo6XmMn8ibjZmNu+uZqnRQNzlElIWpvt8p58ZnoDBA5cIuUEB/btpxvM9mKBggpjw/Iw81SVhsJd9XgGQj7zx4txFPLDU9SEK+HsMrU8PX7k1uULdP0xgJZ9BSY+X6kNYbiPkfrmWnHpQmWJo4jCfMuUaUgpAuSid0sL05oQfdj7I/fhUFPgN/au4j57FkNVCv2v9WN34poQN1CbM92ROPKqoggTarqW+PINHIMzghLkyhovsjFLnxhOZkWLXDirwQ62trd6Etm49LI+GAQRmyeuYlET84IoIVC52zyzANjSfzcxzz/Ky54Y2vdHtPanDKzt6nWu9dO8ip+bYOSBiLT39EZ0sOWN5n7aLBVoqzWXaunOeNlKOP0PjKJeHA78U3JowzlZtth3bck45LpR11o/mPj8iMPf3TSUGItDr1pI/dhMx3UN2UZyzlswgU7uXuDtVsnBNO691gDp8vahiCo9yx5rJdXYI=
