language: java
  
jdk:
  - oraclejdk8

branches:
  only:
     - master
     - desenvolvimento

addons:
  sonarqube:
      organization: "amandapersampa-github"
      token: 
          secure: "L1PkiH+EiL++DJDTTAL3NMpbA1o5roezZppn1H/M80BojBI/1/6PBD/avdUUBIEFEWWupqoDY/IGbTm76FuK6ishkOGqOcCCo3abegcMi4lJp6TOIIRCIlR1r/fqiO56KY+7Aduxp++BD+yeTEGRMEAC+44qc3UgJWIsvpx9LdHOdz+IUYRitovhdYov1xZ5un0KABbYQbWwY7q1w66Y6zjQT5tBo3fKnTR6BVrfgZwVkYdlEvHNYk60Wln8ul+jJWuBRVRpvo6lR4h8iCuqnrLQxCecoORsn0oGsbqsp3wnhrF8s7gO/V50kfEfZ1gZ1kZdrssIpN/SlvXU+7NeI+8xO7tm2UPLq57NBU5Iy9lyx5tV0piBXCc1CEA51I+yD4ZiC1mFO7tLvBUpx8mxCXINXg4Y7RHv9kd2yn5BwpjRZU1894gyNeJkWd5/8XCsfmxNc68aSeCBUa+DX5rykiN/XEDog7ESC8qI3fkXDhqh1JZPi9LsTw0mXP1QyPxRY/wHOxwY5PssqqntAhpb3abfAo45jXhib9RppT8yChRmeMRiTxEnbU4t/a0BXKOZwJ+1vUSQV6Nr8Iw/jAH7uAiYdLXg2kCntj3It9YZOKCG/x8PeFu1ogNZyoiVysv9yEV+k8nvz/xHVM22hSDlXR0k+gxc3BbX1p6vzv6iV9g="

install:
  - sudo pip install -r requirements.txt
  - sudo python setup.py sdist
      
script:
  - sonar-scanner

notifications:
slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG
