language: python
python:
  - 3.6
  - pypy-5.3.1

install:
  pip install -r requirements.txt

script: pytest

addons:
  sonarqube:
    token:16fb7ebe10d4e0f5ca43f8eb9b749ab4f093130a

notifications:
  slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG