language: java
  
jdk:
  - oraclejdk8

branches:
  only:
     - master
     - desenvolvimento

addons:
  sonarqube:
    token: 076efcd77d46ccc1abb6bd17ab4b0db7ea5f13c6

install:
  - sudo pip install -r requirements.txt
  - sudo python setup.py sdist
      
script:
  - sonar-scanner

notifications:
slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG
