language: java

sudo: required
  
jdk:
  - oraclejdk8

branches:
  only:
     - master
     - desenvolvimento

addons:
  sonarqube:
    token: 9ea38151981811489476381738d2cfb17a2fc66b

install: sudo pip install -r requirements.txt
    
script:
  - sonar-scanner -X

notifications:
slack: trabalho-de-les-20171:VPGJMy9q3QpahFd5WXIQ6xTG
